In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
import os

In [2]:
# Load your trained model
model = tf.keras.models.load_model("model_file.h5")

# Path to your test dataset
test_dir = r"C:\Users\kezin\Downloads\archive\test"  # Update this to your test image folder

# Image parameters (should match your model's input size)
IMG_SIZE = (48, 48)  # Update if different
BATCH_SIZE = 32  # Adjust batch size as needed

# Load test images using ImageDataGenerator
test_datagen = ImageDataGenerator(rescale=1./255)  # Normalize images
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',  # Ensures labels are one-hot encoded
    color_mode='grayscale',  # Force grayscale images (fix for input shape mismatch)
    shuffle=False  
)

# Get true labels
y_true = test_generator.classes
class_labels = list(test_generator.class_indices.keys())  # Get class names

# Predict on test data
y_pred_probs = model.predict(test_generator)
y_pred = np.argmax(y_pred_probs, axis=1)  # Convert probabilities to class labels

# Calculate metrics
accuracy = accuracy_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred, average="weighted")
conf_matrix = confusion_matrix(y_true, y_pred)
report = classification_report(y_true, y_pred, target_names=class_labels)

# Print results
print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(report)


Found 7178 images belonging to 7 classes.


c:\Users\kezin\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


225/225 ━━━━━━━━━━━━━━━━━━━━ 11s 49ms/step
Accuracy: 0.2310
F1 Score: 0.2267
Confusion Matrix:
[[227 218  22 186  44 106 155]
 [ 12  46   1  19  10   5  18]
 [170 256  30 164  49  80 275]
 [276 337  61 544 124 162 270]
 [195 345  34 265 128 147 119]
 [254 278  28 266  68 195 158]
 [ 67 122   9  82  29  34 488]]

Classification Report:
              precision    recall  f1-score   support

       angry       0.19      0.24      0.21       958
     disgust       0.03      0.41      0.05       111
        fear       0.16      0.03      0.05      1024
       happy       0.36      0.31      0.33      1774
     neutral       0.28      0.10      0.15      1233
         sad       0.27      0.16      0.20      1247
    surprise       0.33      0.59      0.42       831

    accuracy                           0.23      7178
   macro avg       0.23      0.26      0.20      7178
weighted avg       0.27      0.23      0.23      7178

