In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix,classification_report
import os

# Load your trained model
model = tf.keras.models.load_model(r"C:\Users\kezin\OneDrive\Documents\Codes\python\Projects\Emotion_detection\Custom\CNN\custom\model_file.h5")

# Path to your test dataset
test_dir = r"C:\Users\kezin\Downloads\archive\test"  # Update this to your test image folder

# Image parameters (should match your model's input size)
IMG_SIZE = (48, 48)  # Update if different
BATCH_SIZE = 32  # Adjust batch size as needed

# Load test images using ImageDataGenerator
test_datagen = ImageDataGenerator(rescale=1./255)  # Normalize images
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',  # Ensures labels are one-hot encoded
    color_mode='grayscale',  # Force grayscale images (fix for input shape mismatch)
    shuffle=False  
)


# Get true labels
y_true = test_generator.classes

# Predict on test data
y_pred_probs = model.predict(test_generator)
y_pred = np.argmax(y_pred_probs, axis=1)

# Calculate metrics
accuracy = accuracy_score(y_true, y_pred)
f1 = f1_score(y_true, y_pred, average="weighted")
conf_matrix = confusion_matrix(y_true, y_pred)
report = classification_report(y_test, y_pred_class)

# Print results
print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print("Confusion Matrix:")
print(conf_matrix)


Found 7178 images belonging to 7 classes.


c:\Users\kezin\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


225/225 ━━━━━━━━━━━━━━━━━━━━ 8s 34ms/step
Accuracy: 0.5687
F1 Score: 0.5626
Confusion Matrix:
[[ 430    1  107   79  140  165   36]
 [  53   16   11    5    7   17    2]
 [ 126    1  319   59  154  244  121]
 [  50    0   51 1467  107   60   39]
 [  77    1  107  108  686  217   37]
 [ 139    0  153   93  245  585   32]
 [  29    1  105   62   39   16  579]]


In [ ]:
from sklearn.metrics import accuracy_score, f1_score, classification_report

y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype("int32")

accuracy = accuracy_score(y_test, y_pred_class)
f1 = f1_score(y_test, y_pred_class)
report = classification_report(y_test, y_pred_class)

print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Classification Report:\n", report)
